<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hexagonal_ddd" nsURI="http://a.b.c/x/y/Z" nsPrefix="p">
  <eClassifiers xsi:type="ecore:EClass" name="Hexagon">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="core" lowerBound="1" eType="#//DomainCore"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ports" upperBound="-1"
        eType="#//Port" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="adapters" upperBound="-1"
        eType="#//Adapter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="services" upperBound="-1"
        eType="#//ApplicationService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainCore">
    <eStructuralFeatures xsi:type="ecore:EReference" name="aggregates" upperBound="-1"
        eType="#//AggregateRoot" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="applicationservice" upperBound="-1"
        eType="#//ApplicationService" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AggregateRoot" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalEntities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//ValueObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="#//DomainObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//ValueObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueObject" eSuperTypes="#//DomainObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InboundPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutboundPort" eSuperTypes="#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="Adapter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" lowerBound="1"
        eType="#//Port"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InboundAdapter" eSuperTypes="#//Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutboundAdapter" eSuperTypes="#//Adapter"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectsThrough" upperBound="-1"
        eType="#//Adapter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ApplicationService">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedThrough" upperBound="-1"
        eType="#//InboundPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinates" upperBound="-1"
        eType="#//AggregateRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calls" upperBound="-1"
        eType="#//OutboundPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="useCases" upperBound="-1"
        eType="#//UseCase" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UseCase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Attribute" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
